spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost/springboot_sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8081
env: dev